### ISSUE TITLE
Expected 4. Got 2

### ISSUE THREAD

**Issue by ZehCnaS34** [tree-sitter/tree-sitter-cli#25] opened 2017-10-19 02:33 UTC
Hello,

I'm trying to make an xml tree sitter but I'm running into some issues.

I first create the `grammar.js` file then generate the parser with `tree-sitter-cli generate`. From there I run `node-gyp configure && node-gyp build`. Finally I run `tree-sitter parse test.html` and receive the following.

```
/home/alex/Projects/tree-sitter-xml/node_modules/tree-sitter-cli/lib/cli/parse.js:11
  const document = new Document().setLanguage(language);
                                  ^

RangeError: Incompatible language version. Expected 4. Got 2
    at parse (/home/alex/Projects/tree-sitter-xml/node_modules/tree-sitter-cli/lib/cli/parse.js:11:35)
    at Object.<anonymous> (/home/alex/Projects/tree-sitter-xml/node_modules/tree-sitter-cli/cli.js:57:31)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by maxbrunsfeld** [comment] 2017-10-30 19:11
It looks like you might have incompatible versions of `tree-sitter-cli` and `tree-sitter`? Can you try `rm -rf node_modules/tree-sitter*` and re-running `tree-sitter generate && node-gyp build`?

**Comment by maxbrunsfeld** [comment] 2018-02-01 05:35
I'm going to close this out, because I believe I've described the cause in the comment above. Please let me know if you're still running into this, and I can reopen.

**Closed by maxbrunsfeld** 2018-02-01 05:35 UTC

**Comment by albfan** [comment] 2019-01-12 18:51
@ZehCnaS34 can you share the XML parser? I'm looking for one, see https://github.com/tree-sitter/tree-sitter/issues/266
